"""Default accident DB/report payload sample."""

DB_PAYLOAD = {
    "workplaces": {
        "id": 182,
        "company_name": "(주)스파일럿건설",
        "business_reg_no": "123-45-67890",
        "ceo_name": "김대표",
        "industry_code": "F42132",
        "address": "서울특별시 중구 도로변 상가건물 외벽 보수 현장",
        "total_workers": 18,
        "direct_workers": 10,
        "contracted_workers": 8,
        "safety_health_manager": "E씨",
        "safety_manager_name": "A씨",
        "safety_manager_contact": "010-0000-0018",
        "workers_comp_no": "WC-2023-0018",
        "created_at": "2023-07-09T09:00:00",
    },
    "users": {
        "id": 3,
        "workplace_id": 182,
        "email": "safety18@example.com",
        "name": "이안전",
        "role": "user",
        "password_hash": "<managed-by-auth-server>",
        "created_at": "2023-07-09T09:00:00",
    },
    "cctv_events": {
        "id": 18201,
        "workplace_id": 182,
        "camera_id": "Camera 15",
        "zone_id": "sidewalk_scaffold_zone",
        "detected_at": "2023-07-09T09:32:00",
        "label": "fatal_scaffold_fall",
        "confidence": 0.9,
        "clip_path": "video/accident_video.mp4",
        "clip_start_offset": 0.0,
        "clip_end_offset": 18.5,
        "agent_verdict": "accident",
        "agent_summary": "CCTV 화면상 RED ZONE으로 표시된 비계 하부 위험구역에서 하부 작업자 B씨가 이동식 비계를 임의로 이동시키다가 비계가 전도되어 상부 작업자 C씨가 추락ㆍ사망한 사고로 판단됨.",
        "is_incident_trigger": 1,
        "created_at": "2023-07-09T09:32:30",
    },
    "evidence_photos": [
        {
            "id": 182001,
            "event_id": 18201,
            "incident_id": 18201,
            "photo_url": "output/evidence/accident_video_option2_12s.jpg",
            "detected_label": "worker_on_mobile_scaffold",
            "confidence": 0.84,
            "taken_at": "2023-07-09T09:32:01",
            "source_type": "cctv_capture",
            "is_representative": 0,
            "created_at": "2023-07-09T09:32:35",
        },
        {
            "id": 182002,
            "event_id": 18201,
            "incident_id": 18201,
            "photo_url": "output/evidence/accident_video_option2_18s.jpg",
            "detected_label": "fatal_fall_after_scaffold_instability",
            "confidence": 0.88,
            "taken_at": "2023-07-09T09:32:06",
            "source_type": "cctv_capture",
            "is_representative": 1,
            "created_at": "2023-07-09T09:32:36",
        },
    ],
    "tts_alert_logs": {
        "id": 18201,
        "event_id": 18201,
        "camera_id": "Camera 15",
        "zone_id": "sidewalk_scaffold_zone",
        "language": "ko",
        "message": "추락 사고 발생. 즉시 작업을 중지하고 RED ZONE 및 비계 주변 접근을 통제하십시오.",
        "play_order": 1,
        "audio_url": None,
        "played_at": "2023-07-09T09:32:07",
        "status": "success",
        "created_at": "2023-07-09T09:32:08",
    },
    "incidents": {
        "id": 18201,
        "workplace_id": 182,
        "reported_by": 3,
        "cctv_event_id": 18201,
        "occurred_at": "2023-07-09T09:32:00",
        "location": "건물 1층 외벽 앞 보도, 이동식 비계 설치 구역",
        "accident_type": "추락·전도",
        "accident_grade": "사망",
        "accident_classification": "비계 임의 이동에 따른 전도 및 추락",
        "description": "특별안전교육을 받지 않은 일용직 작업자 C씨가 이동식 비계 위에서 외벽 고정 작업 중, 하부 작업자 B씨가 CCTV RED ZONE 내에서 비계를 임의로 이동시키다가 비계가 전도되어 C씨가 보도 방향으로 추락ㆍ사망함.",
        "equipment_name": "기인물: 이동식 비계 / 관련 설비: 작업발판, 외벽 작업도구",
        "equipment_last_inspection": "2023-06-30",
        "first_finder": "하부 보조작업자 B씨",
        "emergency_call_at": "2023-07-09T09:33:00",
        "labor_report_at": "2023-07-09T10:20:00",
        "emergency_actions": {
            "first_aid": "재해자 상태 확인 후 이동 제한",
            "site_control": "작업중지 및 RED ZONEㆍ비계 주변 통제",
            "report": "119 신고, 고용노동부 중대재해 보고 준비",
        },
        "status": "review",
        "created_at": "2023-07-09T09:35:00",
    },
    "victims": {
        "id": 18201,
        "incident_id": 18201,
        "name": "C씨",
        "age": 47,
        "gender": "M",
        "occupation": "외벽 보수 작업자",
        "tenure": "당일 투입",
        "injury_part": "두부, 흉부, 허리",
        "injury_severity": "사망",
        "first_aid": "119 구급대 인계 전 심정지 의심 상태 확인",
        "hospital": "서울중앙병원",
        "treatment_summary": "병원 이송 후 사망 판정",
        "admission_date": "2023-07-09",
        "expected_discharge": None,
        "estimated_recovery": "해당 없음",
        "workers_comp_filed": 1,
    },
    "incident_details": {
        "id": 18201,
        "incident_id": 18201,
        "timelines": [
            {"time": "09:31:53", "event": "CCTV 관제 화면상 비계 하부와 주변 보행로 일부가 빨간 사각형 RED ZONE으로 표시된 상태에서 C씨가 이동식 비계 위 외벽 작업을 수행함."},
            {"time": "09:32:01", "event": "하부 작업자 B씨가 RED ZONE 내 비계 하부로 접근함."},
            {"time": "09:32:04", "event": "B씨가 현장 관리자 A씨의 승인 없이 비계를 임의로 이동시키려 하면서 비계가 흔들리고 전도됨."},
            {"time": "09:32:06", "event": "비계 전도 영향으로 상부 작업자 C씨가 보도 방향으로 추락함."},
            {"time": "09:33:00", "event": "119 신고 및 현장 작업중지."},
            {"time": "10:20:00", "event": "고용노동부 중대재해 보고 준비."},
        ],
        "witness_statements": [
            {
                "name": "B씨",
                "statement": "비계 아래쪽 공간을 정리하려고 비계를 조금 이동시키려 했고, 그 순간 비계가 흔들리며 위에서 작업하던 C씨가 떨어졌다.",
            },
            {
                "name": "현장 관리자 A씨",
                "statement": "관제 화면상 비계 하부 위험구역을 RED ZONE으로 표시해 접근 및 임의 이동을 금지했으나, 하부 작업자가 이를 지키지 않고 비계를 움직인 것으로 보인다.",
            },
        ],
        "building": "도로변 상가건물",
        "floor": "1층 외벽 및 보도 상부 작업구역",
        "area_sqm": 24.0,
        "workers_on_duty": 3,
        "lighting_status": "주간 자연광, 시야 양호",
        "floor_condition": "보도 블록, 일부 자재 적치 및 비계 하부 공간 협소",
        "special_notes": {
            "video_observation": "CCTV상 이동식 비계 상부 작업자 C씨, 하부에서 비계를 임의 이동시키는 작업자 B씨, 비계 하부와 주변 보행로 일부를 덮는 빨간 사각형 RED ZONE 오버레이가 확인됨.",
            "fatality": "재해자 C씨 사망",
            "site_manager": "A씨는 RED ZONE 관제 및 현장 통제 담당 현장 관리자",
            "site_superintendent": "D씨는 현장소장으로 현장 작업지휘 및 안전관리 총괄",
            "safety_health_manager": "E씨는 안전보건관리책임자로 사업장 안전보건관리체계 이행 책임자",
            "red_zone": "CCTV 관제 화면상 비계 하부와 주변 보행로 일부가 빨간 사각형 RED ZONE 접근금지 위험구역으로 표시되어 있었음",
            "offender": "하부 작업자 B씨가 CCTV RED ZONE 무단 진입 및 비계 무단 이동으로 사고 직접 원인을 제공한 가해자로 검토됨",
            "victim": "상부 작업자 C씨는 비계 위 고정 작업 중 추락한 피해자로, 현재 시나리오 기준 책임 없음",
            "cause_result_relation": "하부 작업자의 비계 임의 이동(직접 원인) → 비계 전도(중간 원인) → 작업자 추락(결과)",
            "industrial_accident_classification": "기인물은 이동식 비계, 사고 유형은 하부 임의 이동에 따른 비계 전도 및 추락 복합",
            "training": "당일 투입 일용직 근로자 특별안전교육 미실시",
            "risk_assessment": "작업 전 위험성평가 미실시",
            "ppe": "안전모 미착용, 안전대 미착용 및 안전고리 미체결, 도로변 작업용 안전조끼 미착용",
            "fall_prevention": "안전대 미착용 및 안전고리 미체결, 안전난간, 작업발판 고정, 비계 전도방지 조치 확인 필요",
            "red_zone_control": "CCTV RED ZONE 표시에도 하부 작업자의 무단 진입ㆍ비계 무단 이동을 막는 관제 알림, 작업지휘자 배치 또는 현장 작업지휘, 출입통제가 미흡했는지 확인 필요",
            "red_zone_legal_basis": "B씨의 RED ZONE 무단 진입은 산업안전보건기준에 관한 규칙 제14조의 낙하물 위험구역 출입통제 의무와 관련해 검토하고, 사업주의 RED ZONE 관리 미흡은 산업안전보건법 시행규칙 별표 6의 안전보건표지 설치ㆍ관리 및 작업지휘 통제 미흡과 함께 검토",
            "public_access_control": "보행자 통행 구역과 RED ZONE의 구분, 현장 시인성, 안전조끼 미착용에 따른 식별성 확보 미흡",
            "contract": "협력업체 도급 작업에 대한 원청 안전보건 확보의무 검토 필요",
        },
        "diagram_svg": None,
        "created_at": "2023-07-09T09:40:00",
    },
    "reports": {
        "id": 18201,
        "incident_id": 18201,
        "created_by": 3,
        "doc_id": "SP-2023-ACCVIDEO-FATAL",
        "status": "draft",
        "pdf_url": None,
        "direct_cause": None,
        "indirect_cause": None,
        "why_items": [],
        "risk_assessments": [],
        "risk_matrix_img_url": None,
        "csa_checks": [],
        "company_fault_pct": None,
        "worker_fault_pct": None,
        "company_reasons": [],
        "worker_reasons": [],
        "legal_risk": None,
        "improvement_actions": [],
        "agent_model": None,
        "accident_summary": None,
        "ai_recommendation": None,
        "final_opinion": None,
        "overall_risk_score": None,
        "signatures": [],
        "published_at": None,
        "created_at": "2023-07-09T09:45:00",
        "updated_at": "2023-07-09T09:45:00",
    },
    "law_references": [],
    "chat_histories": [],
}



